CREATE TABLE IF NOT EXISTS categories (
  `id` INTEGER UNSIGNED PRIMARY KEY,
  `name` VARCHAR(64) NOT NULL UNIQUE,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE frobulators ADD COLUMN IF NOT EXISTS `category_id` INTEGER UNSIGNED;

ALTER TABLE frobulators ADD CONSTRAINT `fk_category_id`
  FOREIGN KEY IF NOT EXISTS (`category_id`) REFERENCES categories (`id`)
  ON DELETE SET NULL;
